package ub;

/* loaded from: classes2.dex */
public enum a {
    DETAIL,
    PENDING,
    COMPLETE_IDENTIFICATION,
    COMPLETE,
    REGISTER_MAIL_ADDRESS,
    NG_IDENTIFICATION,
    REGISTER_IDENTIFICATION,
    EDIT_IDENTIFICATION,
    EDIT_BANK_ACCOUNT,
    SUBMISSION_IDENTIFICATION,
    NONE
}
